In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [38]:
a = np.arange(49,dtype=np.float).reshape((7,7,1))

In [39]:
print(a[0,0], a[0,1] )

[0.] [1.]


In [40]:
data = np.expand_dims(a, axis=0)
data.shape


(1, 7, 7, 1)

In [35]:
mask = np.array( [ [1,0,1],[0,2,0], [1,0,1]], dtype=np.float)
print(mask)

[[1. 0. 1.]
 [0. 2. 0.]
 [1. 0. 1.]]


In [42]:
mask_new = np.expand_dims(np.expand_dims(mask,-1),-1)
mask_new.shape

(3, 3, 1, 1)

In [47]:
res = tf.nn.conv2d(data ,mask_new,strides=1,padding='VALID').numpy()
res.shape

(1, 5, 5, 1)

In [48]:
res.reshape(5,5)

array([[ 48.,  54.,  60.,  66.,  72.],
       [ 90.,  96., 102., 108., 114.],
       [132., 138., 144., 150., 156.],
       [174., 180., 186., 192., 198.],
       [216., 222., 228., 234., 240.]])