In [1]:
# import libs
import numpy as np

In [3]:
# prompt: Generate a random 5 by 5 symmetric matrix and calculate it's eigen values

A = np.random.rand(5, 5)
A = (A + A.T) / 2 + 1.0*np.eye(5)
print(A)
print(np.linalg.eigvals(A))


[[1.46464841 0.51539669 0.60116359 0.32071193 0.80139168]
 [0.51539669 1.09582494 0.40599086 0.56576913 0.59176887]
 [0.60116359 0.40599086 1.06565113 0.33995871 0.36453917]
 [0.32071193 0.56576913 0.33995871 1.48662205 0.60301364]
 [0.80139168 0.59176887 0.36453917 0.60301364 1.37947058]]
[3.39231515 1.21605474 0.46094889 0.60687628 0.81602205]


In [12]:
# prompt: Use QR factorization to repeatatively compute Q,R and the A = RQ
X = A
for _ in range(10):
    Q, R = np.linalg.qr(X)
    X = R@Q
    # X[X < 0.0000000001] = 0
print(np.diag(X))


[3.39231514 1.21604318 0.81598704 0.60691366 0.46095808]


In [15]:
# print(Q)