## Fibonacci

In [1]:
import numpy as np
import plotly.express as px

In [2]:
F = np.array([[1,1],[1,0]])

In [3]:
F

array([[1, 1],
       [1, 0]])

In [13]:
evals, evecs = np.linalg.eig(F)

In [15]:
evecs @ evecs.T 

array([[1., 0.],
       [0., 1.]])

In [6]:
s = np.array([[1,0]]).T
s

array([[1],
       [0]])

In [7]:
F@s

array([[1],
       [1]])

In [11]:
F@F@F@F@F@s

array([[8],
       [5]])

In [14]:
evecs @ np.diag(evals) @ evecs.T

array([[ 1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00, -5.55111512e-17]])

In [12]:
# 100th Fibo number

In [19]:
evecs @ np.diag(evals**10) @ evecs.T @ s

array([[89.],
       [55.]])

In [37]:
F = F.astype(np.int64)
s = np.array([1,0]).reshape((2,1)).astype(np.int64)
fib_values = [ s.flatten() ]
for _ in range(60):
    s_new = F@s
    fib_values.append(s_new.flatten())
    s = s_new


In [38]:
len(fib_values), fib_values[-1]

(61, array([2504730781961, 1548008755920]))

In [41]:
px.scatter(x=[x[0] for x in fib_values], y=[x[1] for x in fib_values], trendline="ols")

In [42]:
fib_values[10]

array([89, 55])

In [44]:
evecs*105

array([[ 89.31833488, -55.20176677],
       [ 55.20176677,  89.31833488]])

## Complex Eigen Vectors

In [46]:
r = np.array([ [0, -1] , [1, 0]  ])

In [47]:
np.linalg.eig(r)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [49]:
D = np.array([ [2, -1] , [0, 1]  ])

In [50]:
np.linalg.eig(D)

(array([2., 1.]),
 array([[1.        , 0.70710678],
        [0.        , 0.70710678]]))