## Hypothesis: Two random vectors in higher dimmension is very likely to be perpendicular

Intersting fact, if we chosse from Normal distribution with mean=0 and Variance = 1/D, the length of the vecs would tend to 1

In [1]:
import numpy as np

In [7]:
D =768
results = []
for i in range(100):
    # Generate 2 random factors of size, D
    # and find their dot products
    f1 = np.random.rand(D) - 0.5
    f2 = np.random.rand(D) - 0.5
    f1 = f1/np.linalg.norm(f1)
    f2 = f2/np.linalg.norm(f2)
    dot_product = np.dot(f1,f2)
    # print(f"{i} # {dot_product= }")
    results.append(dot_product)

print(np.abs(np.mean(results)))

0.0036089290910952657


In [35]:
# do as matrix op
N,D = 10,512 # N samples of D dim vectors
gen = np.random.default_rng(seed=2024)
mat = gen.normal(loc=0.0, scale=np.sqrt(1.0/D), size=(N,D))
# Normalize the vecs to make then Unit length
# mat = mat/np.linalg.norm(mat,axis=1,keepdims=True)
print(mat.shape)
dot_pod = (mat @ mat.T).round(decimals=2)
print(dot_pod.shape)
print(dot_pod)

(10, 512)
(10, 10)
[[ 0.99  0.    0.   -0.06  0.06 -0.02  0.    0.01  0.02  0.02]
 [ 0.    1.08  0.04  0.03  0.02 -0.02  0.    0.03 -0.01 -0.04]
 [ 0.    0.04  1.02 -0.05  0.03  0.07 -0.03 -0.02  0.03 -0.04]
 [-0.06  0.03 -0.05  1.    0.05 -0.01 -0.1  -0.04  0.1  -0.04]
 [ 0.06  0.02  0.03  0.05  0.93 -0.07 -0.08 -0.01 -0.01  0.  ]
 [-0.02 -0.02  0.07 -0.01 -0.07  0.8   0.03 -0.04  0.1  -0.02]
 [ 0.    0.   -0.03 -0.1  -0.08  0.03  1.08 -0.06 -0.02 -0.01]
 [ 0.01  0.03 -0.02 -0.04 -0.01 -0.04 -0.06  0.97  0.07  0.01]
 [ 0.02 -0.01  0.03  0.1  -0.01  0.1  -0.02  0.07  1.08 -0.03]
 [ 0.02 -0.04 -0.04 -0.04  0.   -0.02 -0.01  0.01 -0.03  0.9 ]]


In [34]:
np.linalg.norm(mat,axis=1)

array([0.97697694, 1.0150718 , 1.03518476, 1.04576053, 0.99408847,
       1.02860451, 0.99459035, 1.00498975, 0.95715074, 0.96678226])