In [10]:
import numpy as np
import scipy.linalg as la

In [11]:
A = np.array([
    [1,2,1],
    [2,4,1],
    [3,6,2]
])

l, u = la.lu(A, permute_l=True)
# print(p)
print(l)
print(u)

[[0.33333333 0.         1.        ]
 [0.66666667 1.         0.        ]
 [1.         0.         0.        ]]
[[ 3.          6.          2.        ]
 [ 0.          0.         -0.33333333]
 [ 0.          0.          0.33333333]]


In [12]:
print(np.linalg.matrix_rank(A) , np.linalg.matrix_rank(p))

2 3


In [14]:
B = np.array([
    [3, -7, -2],
    [-3, 5, 1],
    [6, -4, 0]
])
np.linalg.inv(B)

array([[ 0.66666667,  1.33333333,  0.5       ],
       [ 1.        ,  2.        ,  0.5       ],
       [-3.        , -5.        , -1.        ]])

In [ ]:
B = np.array([
    [3, -7, -2],
    [-3, 5, 1],
    [6, -4, 0]
])
np.linalg.inv(B)

In [15]:
from sympy import *

M = Matrix([
    [1, -2, 1, 0],
    [2, 1, -3, 5],
    [4, -7, 1, -2]
])
print("Matrix : {} ".format(M))

# Use sympy.rref() method
M_rref = M.rref()

print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref))

Matrix : Matrix([[1, -2, 1, 0], [2, 1, -3, 5], [4, -7, 1, -2]]) 
The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, 0, 7/2],
[0, 1, 0, 5/2],
[0, 0, 1, 3/2]]), (0, 1, 2))
