PyTorch Droput scales outputs. 

In [10]:
import torch  # pip install torch
import torch.nn as nn
import numpy as np

'''nn.Dropout expects Float '''
test = torch.FloatTensor([1,0,5,2,0,3,6])
# test = np.array([1.0,0,5.0,2.0,0,3.0,6.0])
print(test)  # returns: tensor([1., 0., 5., 2., 0., 3., 6.])

for i in range(2):
    test_with_dropout = nn.Dropout(p=0.25)(test)  # random dropout
    print(test, test_with_dropout)


tensor([1., 0., 5., 2., 0., 3., 6.])
tensor([1., 0., 5., 2., 0., 3., 6.]) tensor([1.3333, 0.0000, 0.0000, 2.6667, 0.0000, 4.0000, 8.0000])
tensor([1., 0., 5., 2., 0., 3., 6.]) tensor([1.3333, 0.0000, 6.6667, 2.6667, 0.0000, 4.0000, 8.0000])


Tensorflow Dropout does not !

In [8]:
# Try with Tensorflow 
import numpy as np
import tensorflow as tf
test = np.array([1.0,0,5.0,2.0,0,3.0,6.0])
for i in range(2):
    tf_dropout_output = tf.keras.layers.Dropout(rate=0.25)(test)  # random dropout
    print(test, tf_dropout_output)

[1. 0. 5. 2. 0. 3. 6.] tf.Tensor([1. 0. 5. 2. 0. 3. 6.], shape=(7,), dtype=float32)
[1. 0. 5. 2. 0. 3. 6.] tf.Tensor([1. 0. 5. 2. 0. 3. 6.], shape=(7,), dtype=float32)
