In [3]:
import tensorflow as tf
import numpy as np

In [4]:
a = np.zeros((3,3,2))
a[0,0,0] = 1
a[0,1,1] = 1
print(a)

[[[1. 0.]
  [0. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [7]:
tf.keras.layers.MaxPooling2D((3,3))(np.reshape(a, (1,3,3,2)))

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[1., 1.]]]], dtype=float32)>

### As observed above the maxpool layres finds the max in each channel independently